---
name: aafm_hymns
description: A new Flutter project.
publish_to: none
version: 1.0.0+9
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  provider: ^6.0.1
  google_nav_bar: ^5.0.5
  line_icons: ^2.0.1
  lottie: ^2.7.0
  flutter_linkify: ^6.0.0
  cool_alert: ^2.0.1
  animated_text_kit: ^4.2.1
  path_provider: ^2.1.3
  material_floating_search_bar_2: ^0.5.0
  awesome_snackbar_content: ^0.1.3
  dependency_validator: ^3.2.3
  # webview_flutter: ^4.7.0
  # flutter_zoom_drawer: ^3.2.0
  formatted_text: ^4.0.1
  google_mobile_ads: ^5.1.0
  firebase_core: ^3.4.1
  firebase_analytics: ^11.3.1
  firebase_app_check: ^0.3.1+1
  firebase_app_installations: ^0.3.1+2
dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.1.8
  flutter_lints: ^3.0.1
flutter:
  uses-material-design: true
  assets:
  - assets/hymns/
  - assets/images/
  - assets/animations/
  fonts:
   - family: Fruktur
     fonts:
       - asset: assets/fonts/Fruktur-Regular.ttf
