---
name: aafm_hymns
description: AAFM In Zimbabwe Hymns.
publish_to: none
version: 1.0.0+9
environment:
  sdk: '>=2.17.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  provider: ^6.1.4
  google_nav_bar: ^5.0.7
  line_icons: ^2.0.1
  lottie: ^2.7.0
  flutter_linkify: ^6.0.0
  cool_alert: ^2.0.1
  animated_text_kit: ^4.2.1
  path_provider: ^2.1.5
  material_floating_search_bar_2: ^0.5.0
  awesome_snackbar_content: ^0.1.3
  dependency_validator: ^4.1.3
  formatted_text: ^4.0.1
  relative_scale: ^2.0.0
  intl: ^0.19.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.1.8
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/hymns/
  - assets/images/
  - assets/animations/
  fonts:
   - family: Fruktur
     fonts:
       - asset: assets/fonts/Fruktur-Regular.ttf
